name: PyPI

on:
   push:
     tags:
       - 'v*'

jobs:
  publish:

    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build and check package
      uses: hynek/build-and-inspect-python-package@v2
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
